// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: customer.sql

package db

import (
	"context"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
  email,
  name,
  hash_password
) VALUES (
  $1, $2, $3
)
RETURNING id, email, name, hash_password, created_at, updated_at
`

type CreateCustomerParams struct {
	Email        string `json:"email"`
	Name         string `json:"name"`
	HashPassword string `json:"hashPassword"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.Email, arg.Name, arg.HashPassword)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers
WHERE id = $1
`

func (q *Queries) DeleteCustomer(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCustomer, id)
	return err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, email, name, hash_password, created_at, updated_at FROM customers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCustomer(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, email, name, hash_password, created_at, updated_at FROM customers
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListCustomersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.HashPassword,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
  set name = $2,
  hash_password = $3
WHERE id = $1
RETURNING id, email, name, hash_password, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	HashPassword string `json:"hashPassword"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer, arg.ID, arg.Name, arg.HashPassword)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
